services:

  postgres:
    image: postgres:15
    restart: unless-stopped  # always чтобы перезапускался постоянно
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      driver: "syslog"
      options:
        syslog-address: "unixgram:///dev/log"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./web
    command: >
      bash -c ' 
        while ! nc -zv postgres 5432; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done &&  
        python manage.py migrate && 
        exec uvicorn web.asgi:application --host 0.0.0.0 --port 8000 --workers 1
      '
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    logging:
      driver: "syslog"
      options:
        syslog-address: "unixgram:///dev/log"
    depends_on:
      - postgres

  bot:
    build: ./bot
    command: >
      bash -c '
        sleep 5 && python main.py && 
        exec uvicorn bot.core.bot_api:app --host 0.0.0.0 --port 8001 --workers 1
      '
    volumes:
      - ./bot:/code
    ports:
      - "8001:8001"
    env_file:
      - .env
    logging:
      driver: "syslog"
      options:
        syslog-address: "unixgram:///dev/log"
    depends_on:
      - postgres
      - web

volumes:
  postgres_data:
