services:
  postgres:
    image: postgres:15
    restart: unless-stopped  # always чтобы перезапускался постоянно
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./web
    command: >
      bash -c ' 
        sleep 5 && 
        python manage.py migrate && 
        uvicorn web.asgi:application --host 0.0.0.0 --port 8000 --workers 1
      '
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  bot:
    build: ./bot
    command: bash -c "sleep 5 && python main.py"
    volumes:
      - ./bot:/code
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
